# Cross.toml - Configuration for cross-compilation

[target.x86_64-unknown-linux-gnu]
pre-build = ["apt-get update && apt-get install -y libpcap-dev"]

[target.i686-unknown-linux-gnu]
pre-build = ["apt-get update && apt-get install -y libpcap-dev"]

[target.aarch64-unknown-linux-gnu]
pre-build = ["apt-get update && apt-get install -y libpcap-dev"]

[target.armv7-unknown-linux-gnueabihf]
pre-build = ["apt-get update && apt-get install -y libpcap-dev"]

[target.arm-unknown-linux-gnueabihf]
pre-build = ["apt-get update && apt-get install -y libpcap-dev"]

[target.mips-unknown-linux-gnu]
pre-build = ["apt-get update && apt-get install -y libpcap-dev"]

[target.mipsel-unknown-linux-gnu]
pre-build = ["apt-get update && apt-get install -y libpcap-dev"]
